### PR TITLE
- Add orn_conv : "ENU_FLU", "NED_FRD" to Aviary, quadx and base_drone…

### PR DESCRIPTION
**Pull request by mchawa**
Add support for ENU_FLU & NED_FRD conventions

- Add "orn_conv" : {"ENU_FLU", "NED_FRD"} to Aviary and make all necessary adjustments
- Add option to plot local axis
- Add examples for NED_FRD usage

### CODE REVIEW

**Comment by mchawa** [comment]
I added support for NED_FRD convention as it is widely used in aviation I think it would be great to add it as a core feature in PyFlyt. I also wanted to make sure the render is showing correctly when NED_FRD is selected thus I didn't do a wrapper as this would basically need to re-write the whole init of Aviary.

**Comment by jjshoots** [comment]
I'll need to think about this a bit more. On a whole, while more support for a common axis convention is a good idea, I don't think this bodes well for PyFlyt's core idea, which is simplicity in understanding. My idea was that, if the user requires a certain axes convention, they can wrap the resulting environment they constructed with a conversion wrapper, sort of like adding an alias within a gymnasium/pz env.

In addition, the changes here will also end up affecting all other vehicles but have not been updated to reflect it. Give me some time to review this, but for now I'm still on the side of the fence that this approach is not ideal.

**Comment by mchawa** [comment]
I actually see your PoV but I found the following problems:

- I wanted to make sure the rendering is done correctly for both axis and using a wrapper I didn't find a neat solution to implement this as I will need to re-write a big part of Aviary anyways.
- My whole objective is basically to develop a custom controller that works with Ardupilot Copter (I will probably create more pull requests related to this), however doing a wrapper around Aviary will be fine during a model training but won't help when I want to simulate the developer controller as any developed controller should be registered to the drone and uses the state inside the drone, thus the only solution will be to bypass this part and use mode "-1" and simulate the controller elsewhere which is also not a clean solution.

**Comment by jjshoots** [comment]
Closing because it's been stale for 3 months, feel free to reopen if more progress is made.

**Pull request closed without merging**
